package com.example.openrewrite;

import org.junit.jupiter.api.Test;
import org.openrewrite.*;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.java.Assertions.mavenProject;
import static org.openrewrite.maven.Assertions.pomXml;


public class MavenParserTest implements RewriteTest {
    @Issue("https://github.com/openrewrite/rewrite/issues/5402")
    @Test
    void allDependencyManagementEntryVariants_allDependencyVariants() {
        rewriteRun(
                mavenProject(
                        "my-bom",
                        pomXml(
                                """
                                  <project>
                                    <groupId>com.mycompany.app</groupId>
                                    <artifactId>my-bom</artifactId>
                                    <version>1</version>
                                    <dependencyManagement>
                                       <dependencies>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <type>jar</type>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <scope>compile</scope>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <type>jar</type>
                                               <scope>compile</scope>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <type>pom</type>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <classifier>sources</classifier>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <classifier>javadoc</classifier>
                                           </dependency>
                                           <dependency>
                                               <groupId>io.flux-capacitor</groupId>
                                               <artifactId>common</artifactId>
                                               <version>0.1148.0</version>
                                               <type>test-jar</type>
                                               <scope>test</scope>
                                           </dependency>
                                       </dependencies>
                                    </dependencyManagement>
                                  </project>
                                  """
                        ),
                        mavenProject(
                                "my-app",
                                pomXml(
                                        """
                                          <project>
                                            <groupId>com.mycompany.app</groupId>
                                            <artifactId>my-app</artifactId>
                                            <version>1</version>
                                            <dependencyManagement>
                                              <dependencies>
                                                <dependency>
                                                  <groupId>com.mycompany.app</groupId>
                                                  <artifactId>my-bom</artifactId>
                                                  <version>1</version>
                                                  <scope>import</scope>
                                                  <type>pom</type>
                                                </dependency>
                                              </dependencies>
                                            </dependencyManagement>
                                            <dependencies>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <type>jar</type>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <scope>compile</scope>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <type>jar</type>
                                                 <scope>compile</scope>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <type>pom</type>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <classifier>sources</classifier>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <classifier>javadoc</classifier>
                                               </dependency>
                                               <dependency>
                                                 <groupId>io.flux-capacitor</groupId>
                                                 <artifactId>common</artifactId>
                                                 <type>test-jar</type>
                                                 <scope>test</scope>
                                               </dependency>
                                            </dependencies>
                                          </project>
                                          """
                                )
                        )
                )
        );
    }

}
